server:
  port: 8081
spring:
  datasource:
    url: ${JDBC_URL:jdbc:mysql://10.16.2.5:3306/hma1?useUnicode=true&characterEncoding=utf8}
    username: ${DB_USER:hma}
    password: ${DB_PASS:hma}
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 10.16.2.1
    port: 5672
    username: ec
    password: ec
    virtual-host: /ec
## 配置普罗米修斯
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'