server:
  port: 8081
spring:
  rabbitmq:
    host: 10.16.2.1
    port: 5672
    username: ec
    password: ec
    virtual-host: /ec

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: '*'